services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: flights
      POSTGRES_USER: flights
      POSTGRES_PASSWORD: flights
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
